[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
axis_auction = "2uB7Hm4yxMwvRWU19QXCvTF9LzTSVrqSGooDYcCZXD7r"

[programs.testnet]
axis_auction = "2uB7Hm4yxMwvRWU19QXCvTF9LzTSVrqSGooDYcCZXD7r"

[provider]
cluster = "testnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test --workspace"

